Update sonarcloud-analysis.yml

diff --git a/.github/workflows/sonarcloud-analysis.yml b/.github/workflows/sonarcloud-analysis.yml
--- a/.github/workflows/sonarcloud-analysis.yml
+++ b/.github/workflows/sonarcloud-analysis.yml
@@ -22,19 +22,25 @@ jobs:
       with:
         python-version: '3.x'  # Specify the Python version you are using
 
-    - name: Install SonarCloud Scan
+    - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install pylint  # Install any necessary packages
-        pip install coverage  # Install any necessary packages
-        pylint **/*.py
+        pip install -vvv pylint  # Install pylint with verbose output for debugging
+
+    - name: Run pylint
+      id: pylint
+      continue-on-error: true  # Continue running even if pylint reports errors
+      run: |
+        set -e  # Ensure script fails on error other than pylint
+        pylint **/*.py || true  # Run pylint and continue regardless of exit code
 
     - name: SonarCloud Scan
+      if: success()  # Only run SonarCloud scan if pylint step succeeds
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       run: |
-        sonar-scanner || true  # Continue even if SonarCloud analysis fails
+        sonar-scanner  # Run SonarCloud scanner
 
     - name: Check SonarCloud Analysis Status
       run: |
