Update sonarcloud-analysis.yml

diff --git a/.github/workflows/sonarcloud-analysis.yml b/.github/workflows/sonarcloud-analysis.yml
--- a/.github/workflows/sonarcloud-analysis.yml
+++ b/.github/workflows/sonarcloud-analysis.yml
@@ -33,7 +33,8 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      run: sonar-scanner || true  # Continue even if SonarCloud analysis fails
+      run: |
+        sonar-scanner || true  # Continue even if SonarCloud analysis fails
 
     - name: Check SonarCloud Analysis Status
       run: |
@@ -43,4 +44,3 @@ jobs:
     - name: Finalize
       if: always()  # Always run this step regardless of previous steps' outcomes
       run: echo "Pipeline completed."
-
